language: node_js
node_js:
- '7'
install:
- npm install
script:
- npm run build
deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after -v $TRAVIS_BUILD_DIR/dist/* deploy@139.59.142.164:/var/www/html/raeddle.aepps.com/
    on:
      branch: master
before_deploy:
- openssl aes-256-cbc -K $encrypted_d998d81e80db_key -iv $encrypted_d998d81e80db_iv
  -in aepp-identity-deploy.enc -out aepp-identity-deploy -d
- eval "$(ssh-agent -s)"
- chmod 600 aepp-identity-deploy
- ssh-add aepp-identity-deploy
- mkdir -p ~/.ssh
- echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
